"""Plan products generated by the Compiler.

* :class:`RuntimePlan` — what each Agent Runtime worker needs to know:
  subscriptions, publish whitelist, fallback policy, guardrail caps.
* :class:`BusTopicPlan` — what the EventBus must ``ensure_topic`` for.

These are pure data — no I/O, no business logic. Higher-layer
modules (Runtime, Orchestrator) consume them.

See ``Doc04 §3`` (compiler), ``Doc02 §3.4`` (default partitions /
retention), ``Doc02 §6`` (DLQ).
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from agentkit.bus.naming import dlq_topic_for
from agentkit.llm.models import LLMBinding


class AgentPlan(BaseModel):
    """Runtime plan for a single Agent template."""

    model_config = ConfigDict(extra="forbid")

    template_key: str
    role: str
    description: str

    # Subscribe table — list of ``(topic_pattern, group_id, tag_filter)``
    subscribe_topics: list[str] = Field(default_factory=list)
    subscribe_tag_filters: list[dict[str, str]] = Field(default_factory=list)
    consumer_group: str = ""

    # Publish whitelist — Runtime PublishPipeline enforces this.
    publish_topics: list[str] = Field(default_factory=list)

    # LLM binding (optional — Memory/Guard nodes may not need LLM).
    llm: LLMBinding | None = None

    # Replica & failure handling
    replica_min: int = 1
    replica_max: int = 1
    fallback: dict[str, Any] | None = None

    # Guardrail caps merged from agent + workflow defaults.
    max_tokens_per_call: int = 8_000
    max_cycles: int = 5

    # Tags propagated as the Runtime's TagIndex defaults.
    tags: dict[str, str] = Field(default_factory=dict)

    # Fan-in aggregation gate (None = event-by-event dispatch).
    aggregate: dict[str, Any] | None = None


class BusTopicSpec(BaseModel):
    """One topic the EventBus must ensure exists."""

    model_config = ConfigDict(extra="forbid")

    topic: str
    partitions: int = 6
    retention_hours: int = 24
    is_dlq: bool = False


class BusTopicPlan(BaseModel):
    """Complete topic provisioning plan for one Workflow."""

    model_config = ConfigDict(extra="forbid")

    topics: list[BusTopicSpec] = Field(default_factory=list)


class RuntimePlan(BaseModel):
    """All artifacts the Runtime + Orchestrator need to bring up a Workflow."""

    model_config = ConfigDict(extra="forbid")

    workflow_id: str
    workflow_version: int
    ir_hash: str

    agents: dict[str, AgentPlan] = Field(default_factory=dict)
    bus_topics: BusTopicPlan = Field(default_factory=BusTopicPlan)

    # LLM bindings registry derived from the IR — can be passed
    # directly to ``LLMGatewayClient(bindings=...)``.
    llm_bindings: dict[str, LLMBinding] = Field(default_factory=dict)

    # Per-Run guardrail caps (authoritative — Orchestrator passes
    # these to Guardrail.init_run_quota).
    run_max_tokens: int = 200_000
    run_max_cycles: int = 200


# ----------------------------------------------------------------
# Helpers used by the Compiler's plan step
# ----------------------------------------------------------------


def derive_dlq_topics(business_topics: list[str]) -> list[BusTopicSpec]:
    """Generate DLQ specs for a list of business topic names."""
    return [
        BusTopicSpec(
            topic=dlq_topic_for(t),
            partitions=6,
            retention_hours=7 * 24,  # 7d default DLQ retention
            is_dlq=True,
        )
        for t in business_topics
    ]
