"""``agentkit`` CLI — Typer app exposing the most common commands.

Phase 1 surface (Doc09 §6, trimmed)::

    agentkit version
    agentkit init <project>
    agentkit validate <yaml-or-py>
    agentkit compile <yaml> [-o <out.json>]
    agentkit schema export [-o <out.json>]
    agentkit run <yaml> --input <json> [--handlers <module>]

Most commands are pure-Python and don't touch external services
(Kafka / Redis / SMTP). ``agentkit run`` uses the in-process
:class:`LocalRuntime` so demos work out-of-the-box.
"""

from __future__ import annotations

import asyncio
import importlib
import json
import sys
from pathlib import Path
from typing import Annotated

import typer

from agentkit import __version__
from agentkit.workflow import compile_from_dict, load_workflow_yaml
from agentkit.workflow.errors import IRValidationError
from agentkit.workflow.ir import WorkflowIR

app = typer.Typer(
    name="agentkit",
    help="AgentKit — distributed event-driven Agent orchestration framework",
    no_args_is_help=True,
    add_completion=False,
)


# ============================================================
# version
# ============================================================


@app.command("version")
def version_cmd() -> None:
    """Print the installed version."""
    typer.echo(f"agentkit {__version__}")


# ============================================================
# init  — scaffold a project
# ============================================================


_INIT_WORKFLOW_YAML = """\
# yaml-language-server: $schema=https://agentkit.dev/schema/1.0.json

id: wf_hello
version: 1
description: "Single-agent demo — echoes back the input."

agents:
  echo:
    role: thinking
    description: "Echoes its input."
    subscribe:
      - topic: q          # → agent.echo.in.q
    publish:
      - topic: reply      # → agent.echo.out.reply
    llm:
      provider: openai
      model: gpt-4o-mini

edges:
  e_in:
    from: __start__
    to: echo
    via: q
  e_out:
    from: echo
    to: __end__
    via: reply
"""

_INIT_HANDLERS_PY = '''\
"""Handler implementations for wf_hello.

Run with::

    agentkit run workflows/wf_hello.yaml \\
        --input \'{"q": "hello world"}\' \\
        --handlers handlers
"""

from agentkit import Event, agent


@agent(role="thinking", subscribe=["q"], publish=["reply"])
async def echo(ctx, event):
    text = event.payload.get("q", "")
    return [Event(topic="reply", payload={"text": text})]
'''

_INIT_README = """\
# {name}

Generated by `agentkit init`. Try::

    agentkit run workflows/wf_hello.yaml --input '{{"q": "hi"}}' --handlers handlers
"""


@app.command("init")
def init_cmd(
    name: Annotated[str, typer.Argument(help="Project directory name")],
    *,
    force: Annotated[
        bool, typer.Option("--force", help="Overwrite existing files"),
    ] = False,
) -> None:
    """Scaffold a new AgentKit project under ``./<name>/``."""
    root = Path(name)
    if root.exists() and not force:
        typer.secho(
            f"✗ {root} already exists — pass --force to overwrite",
            fg=typer.colors.RED, err=True,
        )
        raise typer.Exit(1)
    root.mkdir(parents=True, exist_ok=True)
    (root / "workflows").mkdir(exist_ok=True)
    (root / "handlers.py").write_text(_INIT_HANDLERS_PY, encoding="utf-8")
    (root / "workflows" / "wf_hello.yaml").write_text(
        _INIT_WORKFLOW_YAML, encoding="utf-8",
    )
    (root / "README.md").write_text(
        _INIT_README.format(name=name), encoding="utf-8",
    )
    typer.secho(f"✓ Created {root}/", fg=typer.colors.GREEN)
    typer.echo(f"  Try: cd {name} && agentkit run workflows/wf_hello.yaml --input '{{\"q\":\"hi\"}}' --handlers handlers")


# ============================================================
# validate  — load + compile (without running)
# ============================================================


@app.command("validate")
def validate_cmd(
    path: Annotated[Path, typer.Argument(exists=True, help="Workflow YAML file")],
) -> None:
    """Validate a workflow YAML against the IR schema + compile rules."""
    try:
        raw = load_workflow_yaml(path)
        ir, plan = compile_from_dict(raw)
    except IRValidationError as e:
        typer.secho(f"✗ Validation failed: {e}", fg=typer.colors.RED, err=True)
        for v in (e.violations or []):
            typer.echo(f"  • {v}", err=True)
        raise typer.Exit(1) from None
    except Exception as e:
        typer.secho(f"✗ {type(e).__name__}: {e}", fg=typer.colors.RED, err=True)
        raise typer.Exit(2) from None

    typer.secho(
        f"✓ {ir.id}@v{ir.version}  hash={ir.meta.ir_hash}  "
        f"{len(plan.agents)} agent(s)  {len(plan.bus_topics.topics)} topic(s)",
        fg=typer.colors.GREEN,
    )


# ============================================================
# compile  — output the canonicalized IR JSON
# ============================================================


@app.command("compile")
def compile_cmd(
    path: Annotated[Path, typer.Argument(exists=True, help="Workflow YAML file")],
    *,
    out: Annotated[
        Path | None,
        typer.Option("-o", "--out", help="Output JSON file (default: stdout)"),
    ] = None,
) -> None:
    """Compile a workflow YAML to canonical IR JSON."""
    raw = load_workflow_yaml(path)
    ir, _plan = compile_from_dict(raw)
    text = json.dumps(
        ir.model_dump(by_alias=True, exclude_none=True, mode="json"),
        ensure_ascii=False, indent=2, default=str,
    )
    if out is None:
        typer.echo(text)
    else:
        out.write_text(text, encoding="utf-8")
        typer.secho(f"✓ wrote {out}", fg=typer.colors.GREEN)


# ============================================================
# schema export  — dump the WorkflowIR JSON Schema
# ============================================================


schema_app = typer.Typer(no_args_is_help=True, help="JSON Schema utilities")
app.add_typer(schema_app, name="schema")


@schema_app.command("export")
def schema_export_cmd(
    *,
    out: Annotated[
        Path | None,
        typer.Option("-o", "--out", help="Output file (default: stdout)"),
    ] = None,
) -> None:
    """Export the :class:`WorkflowIR` JSON Schema."""
    schema = WorkflowIR.model_json_schema()
    text = json.dumps(schema, ensure_ascii=False, indent=2)
    if out is None:
        typer.echo(text)
    else:
        out.write_text(text, encoding="utf-8")
        typer.secho(f"✓ wrote {out}", fg=typer.colors.GREEN)


# ============================================================
# run  — execute via LocalRuntime
# ============================================================


@app.command("run")
def run_cmd(
    path: Annotated[Path, typer.Argument(exists=True, help="Workflow YAML file")],
    *,
    input_arg: Annotated[
        str,
        typer.Option(
            "--input", help='JSON input payload (or "@file.json")',
        ),
    ] = "{}",
    handlers_module: Annotated[
        str | None,
        typer.Option(
            "--handlers",
            help="Python module that contains @agent-decorated handlers (e.g. 'handlers')",
        ),
    ] = None,
    timeout: Annotated[
        float, typer.Option("--timeout", help="Seconds to wait for completion"),
    ] = 30.0,
    output_json: Annotated[
        bool, typer.Option("--json", help="Print final Run as JSON instead of pretty"),
    ] = False,
) -> None:
    """Run a workflow locally via the in-process runtime.

    Loads handlers from ``--handlers <module>`` so ``@agent``
    decorators register their templates before compilation.
    """
    payload = _read_input_payload(input_arg)
    if handlers_module:
        # Make CWD importable so user's local handlers.py is found.
        sys.path.insert(0, str(Path.cwd()))
        try:
            mod = importlib.import_module(handlers_module)
        except ImportError as e:
            typer.secho(
                f"✗ Could not import handlers module {handlers_module!r}: {e}",
                fg=typer.colors.RED, err=True,
            )
            raise typer.Exit(1) from None
    else:
        mod = None

    raw = load_workflow_yaml(path)
    ir, plan = compile_from_dict(raw)

    # Walk the user module for @agent-decorated functions whose
    # template_key matches one of the workflow's agents and register
    # them. ``@agent`` itself only attaches metadata; the SDK's
    # ``WorkflowDef.compile()`` does the registration — but the CLI
    # wants to support the looser "YAML + handlers.py" idiom too.
    if mod is not None:
        _register_handlers_from_module(mod, ir.id, ir.agents)

    asyncio.run(_run_workflow(ir, plan, payload, timeout, output_json))


# ============================================================
# serve  — start the FastAPI control plane + Web UI
# ============================================================


@app.command("serve")
def serve_cmd(
    *,
    workflows_dir: Annotated[
        Path,
        typer.Option("--workflows", help="Directory of YAML workflows to deploy"),
    ] = Path("workflows"),
    handlers_module: Annotated[
        str | None,
        typer.Option("--handlers", help="Python module with @agent / Agent definitions"),
    ] = "handlers",
    host: Annotated[str, typer.Option("--host")] = "0.0.0.0",
    port: Annotated[int, typer.Option("--port")] = 8080,
    mock: Annotated[
        bool, typer.Option("--mock", help="Force MockLLMGateway (no key needed)"),
    ] = False,
    deepseek: Annotated[
        bool, typer.Option("--deepseek", help="Use DeepSeek (reads DEEPSEEK_API_KEY)"),
    ] = False,
    mq: Annotated[
        str,
        typer.Option(
            "--mq",
            help="Message-queue backend: auto (default) | memory | kafka | redpanda. "
            "auto → kafka when AGENTKIT_BUS_BROKERS is set in env/.env, else memory.",
        ),
    ] = "auto",
    store: Annotated[
        str,
        typer.Option(
            "--store",
            help="Run-store backend: auto (default) | memory | pg. "
            "auto → pg when AGENTKIT_PG_DSN is set in env/.env, else memory.",
        ),
    ] = "auto",
    guardrail: Annotated[
        str,
        typer.Option(
            "--guardrail",
            help="Quota guardrail backend: auto (default) | memory | redis. "
            "auto → redis when AGENTKIT_GUARDRAIL_REDIS_URL is set in env/.env, else memory.",
        ),
    ] = "auto",
) -> None:
    """Boot the HTTP control plane + Web UI.

    REST endpoints under ``/api/*``; UI bundle (if built) at ``/``.
    Configure provider via ``--mock`` (no key needed) or ``--deepseek``
    (reads ``DEEPSEEK_API_KEY`` from env / ``.env``).

    For stronger durability and horizontal scale, opt into external
    backends::

        agentkit serve --mq kafka --store pg

    Both default to the zero-dependency in-process implementations, so
    plain ``agentkit serve`` needs no Docker / Kafka / Postgres.
    """
    from agentkit.api import serve as _serve  # noqa: PLC0415
    from agentkit.api.backends import (  # noqa: PLC0415
        GUARDRAIL_CHOICES,
        MQ_CHOICES,
        STORE_CHOICES,
    )

    # Validate selectors up-front so the user gets a clean error instead
    # of a stack trace from deep inside the boot sequence.
    for flag, value, choices in (
        ("--mq", mq, MQ_CHOICES),
        ("--store", store, STORE_CHOICES),
        ("--guardrail", guardrail, GUARDRAIL_CHOICES),
    ):
        if value.strip().lower() not in (*choices, "auto"):
            typer.secho(
                f"✗ invalid {flag} {value!r}; choose one of {', '.join(choices)}",
                fg=typer.colors.RED, err=True,
            )
            raise typer.Exit(2)

    typer.secho(f"→ AgentKit serve  http://{host}:{port}", fg=typer.colors.GREEN)
    typer.echo(f"  workflows : {workflows_dir}")
    typer.echo(f"  handlers  : {handlers_module}")
    typer.echo(f"  llm       : {'mock' if mock else ('deepseek' if deepseek else 'auto')}")
    _bk = lambda v: v.lower() + (" (→ resolved from env at boot)" if v.lower() == "auto" else "")  # noqa: E731
    typer.echo(f"  mq        : {_bk(mq)}")
    typer.echo(f"  store     : {_bk(store)}")
    typer.echo(f"  guardrail : {_bk(guardrail)}")
    typer.echo(f"  api docs  : http://{host}:{port}/docs")

    try:
        asyncio.run(_serve(
            workflows_dir=workflows_dir,
            handlers_module=handlers_module,
            host=host, port=port,
            use_mock_llm=mock, deepseek=deepseek,
            mq=mq, store=store, guardrail=guardrail,
        ))
    except KeyboardInterrupt:
        typer.echo("\n(stopped)")


# ============================================================
# Internals
# ============================================================


def _register_handlers_from_module(
    module, workflow_id: str, agent_keys,
) -> None:
    """Match @agent-decorated functions in ``module`` to workflow agents."""
    from agentkit.runtime import HandlerRegistry  # noqa: PLC0415
    from agentkit.runtime.executor import _FunctionExecutor  # noqa: PLC0415
    from agentkit.sdk.decorators import get_agent_meta  # noqa: PLC0415

    reg = HandlerRegistry.global_default()
    for name in dir(module):
        fn = getattr(module, name)
        meta = get_agent_meta(fn)
        if meta is None:
            continue
        if meta.template_key not in agent_keys:
            continue
        reg.register(
            workflow_id=workflow_id,
            template_key=meta.template_key,
            executor=_FunctionExecutor(meta.handler),
            replace=True,
        )


def _read_input_payload(arg: str) -> dict:
    """Decode ``--input`` value: JSON string OR ``@path/to/file.json``."""
    if arg.startswith("@"):
        return json.loads(Path(arg[1:]).read_text(encoding="utf-8"))
    return json.loads(arg)


async def _run_workflow(ir, plan, payload, timeout, output_json) -> None:
    from agentkit.bus.inprocess import InProcessEventBus  # noqa: PLC0415
    from agentkit.orchestrator import InMemoryRunStore, Orchestrator  # noqa: PLC0415
    from agentkit.runtime import AgentWorker, HandlerRegistry  # noqa: PLC0415
    from agentkit.testing.mock_llm import MockLLMGateway  # noqa: PLC0415

    bus = InProcessEventBus()
    await bus.start()
    orch = Orchestrator(bus=bus, store=InMemoryRunStore())
    await orch.start()
    await orch.deploy(ir)

    worker = AgentWorker(
        plan=plan,
        bus=bus,
        llm=MockLLMGateway(reply="(mock reply — supply real LLM via SDK to enable)"),
        handlers=HandlerRegistry.global_default(),
    )
    await worker.start()
    await asyncio.sleep(0.1)

    try:
        run = await orch.create_run(workflow_id=ir.id, input=payload)
        final = await orch.wait_for_completion(run.run_id, timeout=timeout)
    except TimeoutError:
        typer.secho(
            f"✗ Run did not complete within {timeout}s",
            fg=typer.colors.RED, err=True,
        )
        await worker.stop()
        await orch.stop()
        await bus.stop()
        raise typer.Exit(1) from None

    await worker.stop()
    await orch.stop()
    await bus.stop()

    if output_json:
        typer.echo(json.dumps(
            final.model_dump(mode="json"),
            ensure_ascii=False, indent=2, default=str,
        ))
        return

    color = typer.colors.GREEN if final.status.value == "Succeeded" else typer.colors.RED
    typer.secho(
        f"\n✓ run.{final.status.value}  run_id={final.run_id}  "
        f"({len(final.cursor.branch_log)} branch event(s))",
        fg=color,
    )
    if final.failure_reason:
        typer.echo(f"  reason: {final.failure_reason}")
    # Show the last published USER event from the bus as the user-visible
    # output. Skip synthetic ``system.*`` envelopes the orchestrator now
    # publishes for the inbox subsystem (see api/inbox.py).
    user_events = [
        e for e in bus.published if not e.topic.startswith("system.")
    ]
    if user_events:
        last = user_events[-1]
        typer.echo(f"\nlast event on {last.topic}:")
        typer.echo(json.dumps(last.payload, ensure_ascii=False, indent=2, default=str))


# Allow ``python -m agentkit.cli.main``
if __name__ == "__main__":  # pragma: no cover
    app()
